name: Unused

on: push

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Authenticate with private NPM package
        run: echo -e '[install.scopes]\n"@leodurillon" = {url="https://npm.pkg.github.com/", token=${{ secrets.NPM_TOKEN }}}' > ~/.bunfig.toml
      - name: Install dependencies
        run: bun install
      - name: Build app
        run: bun run build
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
